# Generated by Django 4.2.16 on 2025-05-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_conta',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID da Conta'),
        ),
    ]
