# Generated by Django 4.2.16 on 2025-05-31 14:46

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid


def migrate_existing_data(apps, schema_editor):
    """Migrar dados existentes para o novo formato"""
    Account = apps.get_model('accounts', 'Account')
    
    for account in Account.objects.all():
        # Migrar id_conta para account_id
        if hasattr(account, 'id_conta') and account.id_conta:
            account.account_id = account.id_conta
        
        # Migrar client para access_key_id
        if hasattr(account, 'client') and account.client:
            account.access_key_id = account.client
        
        # Migrar secret para secret_access_key
        if hasattr(account, 'secret') and account.secret:
            account.secret_access_key = account.secret
        
        # Definir valores padrão para novos campos
        account.account_type = 'iam'
        account.default_region = 'us-east-1'
        account.enabled_regions = []
        account.status = 3  # Em Validação
        account.is_validated = False
        account.max_instances = 20
        account.max_storage_gb = 1000
        account.tags = {}
        
        account.save()


def reverse_migrate_data(apps, schema_editor):
    """Reverter migração de dados"""
    Account = apps.get_model('accounts', 'Account')
    
    for account in Account.objects.all():
        # Reverter account_id para id_conta
        if hasattr(account, 'account_id') and account.account_id:
            account.id_conta = account.account_id
        
        # Reverter access_key_id para client
        if hasattr(account, 'access_key_id') and account.access_key_id:
            account.client = account.access_key_id
        
        # Reverter secret_access_key para secret
        if hasattr(account, 'secret_access_key') and account.secret_access_key:
            account.secret = account.secret_access_key
        
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id_conta'),
    ]

    operations = [
        # Adicionar novos campos com valores padrão temporários
        migrations.AddField(
            model_name='account',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='000000000000', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Account ID deve ter 12 dígitos')], verbose_name='AWS Account ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('root', 'Root Account'), ('iam', 'IAM User'), ('role', 'IAM Role'), ('federated', 'Federated User')], default='iam', max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='account',
            name='access_key_id',
            field=models.CharField(default='AKIAIOSFODNN7EXAMPLE', max_length=255, verbose_name='Access Key ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='secret_access_key',
            field=models.TextField(default='wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY', verbose_name='Secret Access Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='session_token',
            field=models.TextField(blank=True, null=True, verbose_name='Session Token'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_region',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('eu-west-1', 'Europe (Ireland)'), ('eu-west-2', 'Europe (London)'), ('eu-west-3', 'Europe (Paris)'), ('eu-central-1', 'Europe (Frankfurt)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('sa-east-1', 'South America (São Paulo)'), ('ca-central-1', 'Canada (Central)')], default='us-east-1', max_length=20, verbose_name='Região Padrão'),
        ),
        migrations.AddField(
            model_name='account',
            name='enabled_regions',
            field=models.JSONField(blank=True, default=list, help_text='Lista de regiões onde a conta pode operar', verbose_name='Regiões Habilitadas'),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ativa'), (1, 'Inativa'), (2, 'Suspensa'), (3, 'Em Validação'), (4, 'Erro de Conexão')], default=3, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Validada'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Validação'),
        ),
        migrations.AddField(
            model_name='account',
            name='validation_error',
            field=models.TextField(blank=True, null=True, verbose_name='Erro de Validação'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alias da Conta'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email da Conta'),
        ),
        migrations.AddField(
            model_name='account',
            name='organization_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization ID'),
        ),
        migrations.AddField(
            model_name='account',
            name='max_instances',
            field=models.IntegerField(default=20, verbose_name='Máximo de Instâncias'),
        ),
        migrations.AddField(
            model_name='account',
            name='max_storage_gb',
            field=models.IntegerField(default=1000, verbose_name='Máximo de Storage (GB)'),
        ),
        migrations.AddField(
            model_name='account',
            name='monthly_budget_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento Mensal (USD)'),
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tags'),
        ),
        
        # Migrar dados existentes
        migrations.RunPython(migrate_existing_data, reverse_migrate_data),
        
        # Remover campos antigos
        migrations.RemoveField(
            model_name='account',
            name='id_conta',
        ),
        migrations.RemoveField(
            model_name='account',
            name='client',
        ),
        migrations.RemoveField(
            model_name='account',
            name='secret',
        ),
        
        # Atualizar Meta
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['nome'], 'verbose_name': 'Conta AWS', 'verbose_name_plural': 'Contas AWS'},
        ),
        
        # Criar novos modelos
        migrations.CreateModel(
            name='AccountRegion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('region_code', models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('eu-west-1', 'Europe (Ireland)'), ('eu-west-2', 'Europe (London)'), ('eu-west-3', 'Europe (Paris)'), ('eu-central-1', 'Europe (Frankfurt)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('sa-east-1', 'South America (São Paulo)'), ('ca-central-1', 'Canada (Central)')], max_length=20, verbose_name='Região')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('is_default', models.BooleanField(default=False, verbose_name='Região Padrão')),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('usu_cad', models.CharField(max_length=255, verbose_name='Usuário de Cadastro')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Região da Conta',
                'verbose_name_plural': 'Regiões das Contas',
                'db_table': 'account_regions',
            },
        ),
        migrations.CreateModel(
            name='AccountService',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50, verbose_name='Nome do Serviço')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação')),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('usu_cad', models.CharField(max_length=255, verbose_name='Usuário de Cadastro')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Serviço da Conta',
                'verbose_name_plural': 'Serviços das Contas',
                'db_table': 'account_services',
            },
        ),
        
        # Adicionar constraints
        migrations.AlterUniqueTogether(
            name='accountregion',
            unique_together={('account', 'region_code')},
        ),
        migrations.AlterUniqueTogether(
            name='accountservice',
            unique_together={('account', 'service_name')},
        ),
    ]
