# Generated by Django 4.2.16 on 2025-05-31 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('versao', models.CharField(max_length=255, verbose_name='Versão')),
                ('num_serie', models.CharField(max_length=255, verbose_name='Número de Série')),
                ('alg_assin', models.CharField(max_length=255, verbose_name='Algoritmo de Assinatura')),
                ('alg_hash_assin', models.CharField(max_length=255, verbose_name='Algoritmo Hash de Assinatura')),
                ('emissor', models.CharField(max_length=255, verbose_name='Emissor')),
                ('valid_ini', models.DateField(verbose_name='Validade Inicial')),
                ('valid_fim', models.DateField(verbose_name='Validade Final')),
                ('requerente', models.CharField(max_length=255, verbose_name='Requerente')),
                ('chave_pub', models.TextField(verbose_name='Chave Pública')),
                ('chave_pub_param', models.TextField(verbose_name='Parâmetros da Chave Pública')),
                ('status', models.IntegerField(choices=[(0, 'Ativo'), (1, 'Inativo'), (2, 'Expirado'), (3, 'Revogado'), (4, 'Pendente')], default=0, verbose_name='Status')),
                ('arquivo', models.BinaryField(verbose_name='Arquivo do Certificado')),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('usu_cad', models.CharField(max_length=255, verbose_name='Usuário de Cadastro')),
                ('data_atu', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
                ('usu_atu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário de Atualização')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificates',
            },
        ),
    ]
