# Generated by Django 4.2.16 on 2025-05-31 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Recurso')),
                ('tipo', models.IntegerField(choices=[(0, 'S3'), (1, 'Load Balancer'), (2, 'CloudFront'), (3, 'API Gateway'), (4, 'EC2'), (5, 'RDS'), (6, 'Lambda')], verbose_name='Tipo do Recurso')),
                ('url', models.URLField(verbose_name='URL do Recurso')),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('usu_cad', models.CharField(max_length=255, verbose_name='Usuário de Cadastro')),
                ('data_atu', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
                ('usu_atu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário de Atualização')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'resources',
            },
        ),
    ]
