# Generated by Django 4.2.16 on 2025-05-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='senha',
        ),
        migrations.AlterField(
            model_name='user',
            name='usu_cad',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usuário de Cadastro'),
        ),
    ]
