# Generated by Django 4.2.16 on 2025-06-01 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20250531_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout')),
                ('widgets', models.JSONField(default=list, verbose_name='Widgets')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.CharField(max_length=255, verbose_name='Criado por')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários Permitidos')),
            ],
            options={
                'verbose_name': 'Dashboard de Monitoramento',
                'verbose_name_plural': 'Dashboards de Monitoramento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Orçamento')),
                ('period', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=20, verbose_name='Período')),
                ('threshold_percentage', models.IntegerField(default=80, verbose_name='Porcentagem de Alerta (%)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação')),
                ('current_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gasto Atual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.CharField(max_length=255, verbose_name='Criado por')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta AWS')),
            ],
            options={
                'verbose_name': 'Alerta de Custo',
                'verbose_name_plural': 'Alertas de Custo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('metric', models.CharField(choices=[('cpu_utilization', 'CPU Utilization'), ('memory_utilization', 'Memory Utilization'), ('disk_utilization', 'Disk Utilization'), ('network_in', 'Network In'), ('network_out', 'Network Out'), ('instance_count', 'Instance Count'), ('s3_bucket_size', 'S3 Bucket Size'), ('rds_connections', 'RDS Connections'), ('lambda_invocations', 'Lambda Invocations'), ('lambda_errors', 'Lambda Errors'), ('lambda_duration', 'Lambda Duration'), ('cost_daily', 'Daily Cost'), ('cost_monthly', 'Monthly Cost')], max_length=50, verbose_name='Métrica')),
                ('operator', models.CharField(choices=[('gt', 'Greater Than (>)'), ('gte', 'Greater Than or Equal (>=)'), ('lt', 'Less Than (<)'), ('lte', 'Less Than or Equal (<=)'), ('eq', 'Equal (=)'), ('ne', 'Not Equal (!=)')], max_length=10, verbose_name='Operador')),
                ('threshold', models.FloatField(verbose_name='Limite')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severidade')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Notificar por Email')),
                ('notify_slack', models.BooleanField(default=False, verbose_name='Notificar por Slack')),
                ('slack_webhook', models.URLField(blank=True, verbose_name='Webhook Slack')),
                ('check_interval', models.IntegerField(default=5, verbose_name='Intervalo de Verificação (minutos)')),
                ('cooldown_period', models.IntegerField(default=30, verbose_name='Período de Cooldown (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.CharField(max_length=255, verbose_name='Criado por')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta AWS')),
            ],
            options={
                'verbose_name': 'Regra de Alerta',
                'verbose_name_plural': 'Regras de Alerta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('current_value', models.FloatField(verbose_name='Valor Atual')),
                ('threshold_value', models.FloatField(verbose_name='Valor Limite')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido'), ('suppressed', 'Suprimido')], default='open', max_length=20, verbose_name='Status')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Disparado em')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('acknowledged_by', models.CharField(blank=True, max_length=255, verbose_name='Reconhecido por')),
                ('resolved_by', models.CharField(blank=True, max_length=255, verbose_name='Resolvido por')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta AWS')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.alertrule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100, verbose_name='Nome da Métrica')),
                ('namespace', models.CharField(max_length=100, verbose_name='Namespace')),
                ('dimensions', models.JSONField(default=dict, verbose_name='Dimensões')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unidade')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta AWS')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account', 'metric_name', 'timestamp'], name='monitoring__account_dfddd3_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_a57f02_idx')],
            },
        ),
    ]
