# Generated by Django 4.2.16 on 2025-06-01 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250531_1446'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringdashboard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.RemoveIndex(
            model_name='metric',
            name='monitoring__account_dfddd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='metric',
            name='monitoring__timesta_a57f02_idx',
        ),
        migrations.RemoveField(
            model_name='costalert',
            name='budget_amount',
        ),
        migrations.RemoveField(
            model_name='costalert',
            name='current_spend',
        ),
        migrations.RemoveField(
            model_name='costalert',
            name='last_check',
        ),
        migrations.RemoveField(
            model_name='costalert',
            name='threshold_percentage',
        ),
        migrations.RemoveField(
            model_name='monitoringdashboard',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='monitoringdashboard',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='monitoringdashboard',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='monitoringdashboard',
            name='widgets',
        ),
        migrations.AddField(
            model_name='costalert',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Notificar por Email'),
        ),
        migrations.AddField(
            model_name='costalert',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Limite (USD)'),
        ),
        migrations.AddField(
            model_name='metric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoringdashboard',
            name='config',
            field=models.JSONField(default=dict, verbose_name='Configuração'),
        ),
        migrations.AddField(
            model_name='monitoringdashboard',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Dashboard Padrão'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='check_interval',
            field=models.IntegerField(default=5, verbose_name='Intervalo de Verificação (min)'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='cooldown_period',
            field=models.IntegerField(default=15, verbose_name='Período de Cooldown (min)'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(max_length=255, verbose_name='Métrica'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='operator',
            field=models.CharField(choices=[('gt', 'Maior que'), ('gte', 'Maior ou igual'), ('lt', 'Menor que'), ('lte', 'Menor ou igual'), ('eq', 'Igual'), ('ne', 'Diferente')], max_length=10, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20, verbose_name='Severidade'),
        ),
        migrations.AlterField(
            model_name='costalert',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='costalert',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dimensões'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_name',
            field=models.CharField(max_length=255, verbose_name='Nome da Métrica'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='namespace',
            field=models.CharField(max_length=255, verbose_name='Namespace'),
        ),
        migrations.AlterField(
            model_name='monitoringdashboard',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('account', 'metric_name', 'namespace', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='metric',
            name='collected_at',
        ),
    ]
