# Generated by Django 4.2.16 on 2025-05-31 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('permission_type', models.CharField(choices=[('users_create', 'Criar Usuários'), ('users_edit', 'Editar Usuários'), ('users_delete', 'Excluir Usuários'), ('users_view', 'Visualizar Usuários'), ('certificates_create', 'Criar Certificados'), ('certificates_edit', 'Editar Certificados'), ('certificates_delete', 'Excluir Certificados'), ('certificates_view', 'Visualizar Certificados'), ('accounts_create', 'Criar Contas'), ('accounts_edit', 'Editar Contas'), ('accounts_delete', 'Excluir Contas'), ('accounts_view', 'Visualizar Contas'), ('resources_create', 'Criar Recursos'), ('resources_edit', 'Editar Recursos'), ('resources_delete', 'Excluir Recursos'), ('resources_view', 'Visualizar Recursos'), ('permissions_create', 'Criar Permissões'), ('permissions_edit', 'Editar Permissões'), ('permissions_delete', 'Excluir Permissões'), ('permissions_view', 'Visualizar Permissões')], max_length=50, verbose_name='Tipo de Permissão')),
                ('granted', models.BooleanField(default=True, verbose_name='Concedida')),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('usu_cad', models.CharField(max_length=255, verbose_name='Usuário de Cadastro')),
                ('data_atu', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
                ('usu_atu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário de Atualização')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'db_table': 'permissions',
            },
        ),
    ]
