# Generated by Django 4.2.16 on 2025-05-31 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('user', 'Usuário'), ('viewer', 'Visualizador')], max_length=50, unique=True, verbose_name='Nome do Role')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('usu_cad', models.CharField(max_length=255, verbose_name='Usuário de Cadastro')),
                ('data_atu', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
                ('usu_atu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário de Atualização')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['user__nome', 'permission_type'], 'verbose_name': 'Permissão', 'verbose_name_plural': 'Permissões'},
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('usu_cad', models.CharField(max_length=255, verbose_name='Usuário de Cadastro')),
                ('data_atu', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
                ('usu_atu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário de Atualização')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Role do Usuário',
                'verbose_name_plural': 'Roles dos Usuários',
                'db_table': 'user_roles',
                'ordering': ['user__nome', 'role__name'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
